### ISSUE TITLE
[Feature Request] Adding more options to Style Settings 

### ISSUE THREAD

**Issue by Xelbayria** [ArtexJay/Obsidian-CyberGlow#50]
**Describe the change you'd like**
I would like a few settings to be added to the style settings. Please see the `Additonal Context` 

**Describe any plug-ins that this change would be affected**
None

**Additional context**
![image](https://user-images.githubusercontent.com/12866666/231325606-1b4c1b71-5e2f-48a0-9f61-9e669b368e09.png)

(A & D) The inactive (unselected note):
- i would like to change the fonts to any colors
- Add the green color to the tab (similar to B) 
---
(B & C) The active (Selected Note): 
- Change fonts to any colors for being selected 
- remove the green color from the tab 
---
( F ) Fonts: 
- change any of these "F" is pointing at, to any color (type by type OR all) 
---
that's it.  I hope it should be simple for you to add to the `Style Setting`. I wasn't able to find these settings in Style Setting. Please let me know if i happened to overcome one. 
---
EDIT: 
Right, I forgot to add three more thing: 
- I would like to know how to change the color of headers from 1 to 6 to my likes? 
- change the color of Quoteblock or quotes or disable it to not be affected by theme (i meant cyberglow) 
- change the color of checkbox or disable it to not be affected by the theme(i have my own custom of checkbox enabled)  
- change the color of bullets or disable it
- change the color of links []() outgoing or in

If that wasn't added to `Style Settings` then please add it, thanks for taking your time to read here. 

---

Tracker
Some listed are:
- [x] change the color of checkbox or disable it to not be affected by the theme (i have my own custom of checkbox enabled)
- [x] change the color of links outgoing or in
- [x] change the color of bullets or disable it
- [x] Change the color of headers from 1 to 6 
- [x] change the color of Quoteblock or quotes or disable it to not be affected by theme (i meant cyberglow)
- [x] change the green color from the tab 
- [x] Change active tab font to any colors for being selected

**Comment by ArtexJay** [comment]
I'll attempt to address and clarify on your suggestions one at a time.
So first the coloring, currently all the coloring is based on the accent color picked within Obsidian. So you'd like to have the ability to change the colors of fonts for A, D and F regardless of what the accent color is currently picked?

Also the header's the should be in the style settings, under "Heading Controls". Though notice that headers 3-6 are are made to use the same fonts as the headings are smaller compared to the earlier headings.
![image](https://user-images.githubusercontent.com/32932497/231569211-a899af54-ef78-43f7-bc7a-5d769edc713e.png)

Getting around to implementing these changes will take some time. I'm still reworking from the ground up the theme, together with my studies. So I am only able to work on it in my free time at the moment. Though I believe it should be finalized soon.

**Comment by Xelbayria** [comment]
👍 
alright, just to give you a good example of what I would to make a change in the theme. 

here's a good look at the screen below, it's a mess, haha. 
![image](https://user-images.githubusercontent.com/12866666/231590952-dcbd9555-0c7b-4812-9618-8c344a4b84cc.png)

As you can use I am using White and Green with dark theme. (it seems that you haven't implemented the system to account for "white") and I am a beginner in modifying the theme using CSS Snippets. it's almost working but there are a few problems as you can see where red arrow are pointing at. :| hmm 

anyway, that's not the final theme that I would like to use for my phone and PC. I have to say what an excellent theme you've created. No rush, I am aware of your life that you need to tend to. Just take your time so no mistake is made.

**Comment by Xelbayria** [comment]
@ArtexJay 
Hello, 
I found one missing features that you forgot to modifying and it doesn't even change the background of codeblock 

```css
.markdown-source-view.mod-cm6 .cm-line.HyperMD-codeblock {
	color: var(--text-muted);
	background: var(--transparency-secondary); 
}

body:not(.no-codeblock-line-numbers) .cm-s-obsidian div.HyperMD-codeblock-begin-bg {
	background-color: var(--code-block-alt-bg);  <- RIGHT HERE
	border: var(--codeblock-border);  <- RIGHT HERE
	border-bottom: 2px;
	border-top-right-radius: 5px !important;
	border-top-left-radius: 5px !important;
	border-image-slice: 1;
	border-image-source: linear-gradient(to right, transparent, var(--text-accent), transparent);
	border-top: 2px solid;
}
```
I was looking for the variables so i can modify it but they do not exist. The background of codeblock is that of "default" looking

Anyway, I am almost finished with the theme. I'm just going through your theme.css and found 2 repeating code (same code). I removed one of them)
