### ISSUE TITLE
[Desktop Bug] Theme Issue with Codeblock's

### ISSUE THREAD

**Issue by Xelbayria** [ArtexJay/Obsidian-CyberGlow#51]
**Describe the bug**
@ArtexJay

I found some issues where the theme doesn't even change the background of codeblock, It looks more like default looking of codeblock. 
```css
.markdown-source-view.mod-cm6 .cm-line.HyperMD-codeblock {
	color: var(--text-muted);
	background: var(--transparency-secondary) !important;  /* <- RIGHT HERE: Needed to be added "!important" to take effect */
}

body:not(.no-codeblock-line-numbers) .cm-s-obsidian div.HyperMD-codeblock-begin-bg {
	background-color: var(--code-block-alt-bg); /* <- RIGHT HERE: (cannot find any reference) */
	border: var(--codeblock-border); /* <- RIGHT HERE: It doesn't existed (cannot find any reference) */
	border-bottom: 2px;
	border-top-right-radius: 5px !important;
	border-top-left-radius: 5px !important;
	border-image-slice: 1;
	border-image-source: linear-gradient(to right, transparent, var(--text-accent), transparent);
	border-top: 2px solid;
}

body:not(.no-codeblock-line-numbers) .cm-s-obsidian div.HyperMD-codeblock-end-bg {
	border-image-slice: 1;
	border-image-source: linear-gradient(to right, transparent, var(--text-accent), transparent);
	border-bottom: 4px solid; /* MODIFIED */
	border-top: none;
}
```

**To Reproduce**
1. create a codeblock using \`\`\` and pick any language, in my case, it was cpp/c++ 
2. add the code inside the codeblock
3. switch to reading mode and editing mode to see the problem. 

**Expected behavior**
I expected the codeblock to have the syntax highlighting and change the background if I modified the theme (it's not working 100%) 

**Screenshots, Gifs, Video**

There is a problem with your theme and the codeblock, here's the original theme:

READING MODE:
![image](https://user-images.githubusercontent.com/12866666/231984726-04d498e6-eb0a-4858-b9d1-a54d3795b33d.png)

U can see it's missing the syntax highlighting

EDITING MODE:
![image](https://user-images.githubusercontent.com/12866666/231984796-dddb6843-dda3-4feb-9a33-712dc8d4de36.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 pro 
 - Obsidian Version: 1.1.16
 - CyberGlow Version: 7.9.0

**Comment by ArtexJay** [comment]
that's strange, I tested it on my version using v7.9 of the theme and running obsidian 1.1.16, I get the correct expected results as you can see in my screenshot.

As for the no reference code, I that is old code I forgot/missed to delete that code. You can delete those two lines.

I tested `	background: var(--transparency-secondary) !important;  /* <- RIGHT HERE: Needed to be added "!important" to take effect */`
This correctly takes effect without needing "!important".


![image](https://user-images.githubusercontent.com/32932497/232874647-2ffcd80f-b5ef-413f-b89e-cb6fdf30aa82.png)

**Comment by ArtexJay** [comment]
Also disable any plugins you may have installed on obsidian that affect codeblocks, if disabling a plugin fixes it, tell me what's the plug in so that my theme may support it

**Comment by Xelbayria** [comment]
> that's strange, I tested it on my version using v7.9 of the theme and running obsidian 1.1.16, I get the correct expected results as you can see in my screenshot.
> As for the no reference code, I that is old code I forgot/missed to delete that code. You can delete those two lines.
> I tested ` background: var(--transparency-secondary) !important; /* <- RIGHT HERE: Needed to be added "!important" to take effect */` This correctly takes effect without needing "!important".
> As such I am unable to replicate your codeblock issue.
> Edit: My suggestion is since you edited my theme, make a backup of your edited version, apply the default theme without your changes and see if you still experience the codeblocks coloring issue that you described. 
> image (removed) 

You may not have noticed this sentence of mine showing "the original theme" 👇 in my previous message : 
> There is a problem with your theme and the codeblock, here's the original theme:

I was using the default theme to check to see if it's just me or a problem with the default theme. My modified theme is added as snippet just to override the `original theme` (everything is working correctly without me messing up) 

Strange enough, I'm seeing the correct result of reading editor and editing mode regarding the syntax highlighting. I have investigated to find out why your result is correct but my result is not correct. 
Ah, it turned out there is a big difference between using "cpp" and "c++". Look like I'll have to use cpp from now. No worries. 

I could use your help, so here's what my modified looks like is below: 

```CSS
.markdown-source-view.mod-cm6 .cm-line.HyperMD-codeblock {
	color: var(--text-muted);
	background: rgba(0, 0, 0, 0.25) !important;
}

body:not(.no-codeblock-line-numbers) .cm-s-obsidian div.HyperMD-codeblock-begin-bg, div.labeled-codeblock.data_h {
	background-color: transparent; /* MODIFIED */
	border: var(--codeblock-border);
	border-bottom: 2px;
	border-top-right-radius: 5px !important;
	border-top-left-radius: 5px !important;
	border-image-slice: 1;
	border-image-source: linear-gradient(to right, transparent, var(--text-accent), transparent);
	border-top: 4px solid; /* MODIFIED */
}

body:not(.no-codeblock-line-numbers) .cm-s-obsidian div.HyperMD-codeblock-end-bg {
	border-image-slice: 1;
	border-image-source: linear-gradient(to right, transparent, var(--text-accent), transparent);
	border-bottom: 4px solid; /* MODIFIED */
	border-top: none;
```

You should be able to noticed that I was trying to make the background a bit more transparency but it's not showing itself correctly in `editor mode` hence why i add `!important` 

Is there a way I can include the modified background of the codeblock via `reading editor` just like `editing mode`.
